//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSQ.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoSQ.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BottomBackGround {
            get {
                object obj = ResourceManager.GetObject("BottomBackGround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cursor {
            get {
                object obj = ResourceManager.GetObject("Cursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macro {
            get {
                object obj = ResourceManager.GetObject("macro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MidBackGround {
            get {
                object obj = ResourceManager.GetObject("MidBackGround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (6,28,53),(6,28,53),(6,28,53),(6,28,53),(7,28,53),(7,28,53),(7,28,54),(8,29,54),(3,55,133),(2,55,133),(2,54,133),(5,29,57),(5,27,53),(5,27,53),(6,29,60),(3,54,132),(3,53,128),(8,30,54),(7,36,76),(3,55,133),(2,55,133),(2,55,133),(5,39,84),(6,28,53),(6,28,53),(6,28,53),(7,29,54),(8,29,54),(8,29,54),(8,29,54),(7,29,54),(6,29,54),(6,28,53),(6,28,53),(7,29,54).
        /// </summary>
        internal static string Protoss {
            get {
                return ResourceManager.GetString("Protoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (6,28,53),(6,28,53),(6,28,53),(6,28,53),(7,28,53),(6,32,64),(3,51,120),(4,51,120),(4,49,112),(6,29,55),(5,28,55),(5,28,56),(2,50,120),(2,50,120),(3,50,120),(3,51,120),(4,51,120),(6,39,83),(7,32,63),(7,32,62),(4,44,101),(4,42,97),(5,38,84),(6,28,53),(6,28,53),(6,28,53),(7,29,54),(8,29,54),(8,29,54),(8,29,54),(7,29,54),(6,29,54),(6,28,53),(6,28,53),(7,29,54).
        /// </summary>
        internal static string Terran {
            get {
                return ResourceManager.GetString("Terran", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap TestBackground {
            get {
                object obj = ResourceManager.GetObject("TestBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TopBackGround {
            get {
                object obj = ResourceManager.GetObject("TopBackGround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (8,29,54),(9,30,54),(9,30,54),(9,30,55),(9,29,54),(9,30,54),(6,45,101),(4,55,133),(5,51,122),(6,46,103),(4,55,133),(4,55,133),(7,40,86),(9,30,54),(6,49,112),(4,55,133),(4,55,133),(4,54,129),(9,32,61),(10,31,58),(4,55,133),(4,55,133),(4,55,134),(4,56,134),(4,56,134),(11,31,56),(10,30,54),(9,30,54),(8,29,54),(8,29,54),(8,29,54),(8,29,54),(8,29,53),(8,29,53),(8,29,53).
        /// </summary>
        internal static string Zerg {
            get {
                return ResourceManager.GetString("Zerg", resourceCulture);
            }
        }
    }
}
